name: 'Terraform generator'
description: 'Generates terraform code that calls terraform module'
author: 'Cloud Posse <hello@cloudposse.com>'
branding:
  icon: 'activity'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.type }}
    - --component
    - ${{ inputs.component }}
    - --module_name
    - ${{ inputs.module_name }}
    - --module_source
    - ${{ inputs.module_source }}
    - --module_attributes
    - ${{ inputs.module_attributes }}
    - --stacks_dir
    - ${{ inputs.stacks_dir }}
    - --stack
    - ${{ inputs.stack }}
    - --stack_source
    - ${{ inputs.stack_source }}
    - --components
    - ${{ inputs.components }}
    - --global_vars
    - ${{ inputs.global_vars }}
    - --imports
    - ${{ inputs.imports }}
inputs:
  type:
    description: 'Whether this is a "stack" or "module"'
    default: "module"
    required: false
  # Note, these are only required for modules:
  component:
    description: 'Component path for output'
    default: '""'
    required: false
  module_name:
    description: 'Module name'
    default: '""'
    required: false
  module_source:
    description: 'Module source'
    default: '""'
    required: false
  module_attributes:
    description: 'Module attributes'
    default: '{}'
    required: false
  # Note, These are only required for stacks:
  stacks_dir:
    description: 'Stacks directory'
    default: '""'
    required: false
  stack:
    description: 'Stack name'
    default: '""'
    required: false
  stack_source:
    description: 'Stack source'
    default: '""'
    required: false
  # Note, these are optional, but only affect stacks when set
  components:
    description: 'Stack components'
    default: '{}'
    required: false
  global_vars:
    description: 'Stack globals'
    default: '{}'
    required: false
  imports:
    description: 'Stack imports'
    default: '[]'
    required: false